apiVersion: v1
kind: Secret
metadata:
  name: docgrok-providers
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  {{- range $name, $provider := .Values.providers }}
  {{- if $provider.enabled }}
  {{ $name }}-api-key: {{ $provider.apiKey | quote }}
  {{- end }}
  {{- end }}
