apiVersion: v1
kind: ServiceAccount
metadata:
  name: docgrok-sa
  namespace: {{ .Values.global.namespace }}
  annotations:
    azure.workload.identity/client-id: "0cbb4225-1aea-45d9-8287-72f83587fd05"
