{{- if .Values.web.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: omnivec-web
  namespace: {{ .Values.global.namespace }}
  labels:
    app: omnivec-web
    {{- include "omnivec.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.web.replicaCount }}
  selector:
    matchLabels:
      app: omnivec-web
  template:
    metadata:
      labels:
        app: omnivec-web
    spec:
      containers:
        - name: web
          image: {{ .Values.global.imageRegistry }}/{{ .Values.web.image.repository }}:{{ .Values.web.image.tag }}
          imagePullPolicy: {{ .Values.web.image.pullPolicy }}
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            {{- toYaml .Values.web.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: {{ .Values.web.probes.liveness.path }}
              port: 8080
            initialDelaySeconds: {{ .Values.web.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.web.probes.liveness.periodSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.web.probes.readiness.path }}
              port: 8080
            initialDelaySeconds: {{ .Values.web.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.web.probes.readiness.periodSeconds }}
---
apiVersion: v1
kind: Service
metadata:
  name: omnivec-web
  namespace: {{ .Values.global.namespace }}
  labels:
    app: omnivec-web
  {{- if .Values.web.service.dnsLabel }}
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: {{ .Values.web.service.dnsLabel | quote }}
  {{- end }}
spec:
  type: {{ .Values.web.service.type }}
  ports:
    - port: {{ .Values.web.service.port }}
      targetPort: {{ .Values.web.service.targetPort }}
      protocol: TCP
  selector:
    app: omnivec-web
{{- end }}
