#!/usr/bin/env python3
"""Create 10 large multi-page PDFs and upload to Azure Blob Storage."""
import fitz
from azure.storage.blob import BlobServiceClient
from azure.identity import DefaultAzureCredential
import logging

for lg in ("azure.core.pipeline.policies.http_logging_policy", "azure.identity", "azure.core", "urllib3"):
    logging.getLogger(lg).setLevel(logging.WARNING)

cred = DefaultAzureCredential()
svc = BlobServiceClient("https://ovstorepqmqe6wvau2gi.blob.core.windows.net", credential=cred)
cc = svc.get_container_client("blobomnivectest")

large_docs = [
    ("Comprehensive Guide to Machine Learning", [
        "Machine learning is a subset of artificial intelligence that enables systems to learn and improve from experience without being explicitly programmed. The field has evolved dramatically since Arthur Samuel coined the term in 1959. Today, machine learning powers everything from email spam filters to autonomous vehicles.",
        "Supervised learning is the most common paradigm. In supervised learning, the algorithm learns from labeled training data. The goal is to learn a mapping function from input variables X to output variables Y. Common supervised algorithms include linear regression, logistic regression, decision trees, random forests, support vector machines, and neural networks.",
        "Unsupervised learning deals with unlabeled data. The system tries to find hidden patterns or intrinsic structures in the input data. Clustering algorithms like K-means, hierarchical clustering, and DBSCAN group similar data points together. Dimensionality reduction techniques like PCA and t-SNE reduce the number of features while preserving important relationships.",
        "Reinforcement learning is inspired by behavioral psychology. An agent learns to make decisions by performing actions in an environment to maximize cumulative reward. Key concepts include states, actions, rewards, policies, and value functions. Q-learning and policy gradient methods are foundational algorithms in this space.",
        "Deep learning uses artificial neural networks with multiple layers (deep architectures) to model complex patterns in data. Convolutional neural networks (CNNs) excel at image recognition. Recurrent neural networks (RNNs) and their variants like LSTMs handle sequential data. Transformers have revolutionized natural language processing with attention mechanisms.",
        "Feature engineering is the process of using domain knowledge to create input features that make machine learning algorithms work better. Good features can make simple algorithms perform well, while poor features can make complex algorithms fail. Techniques include one-hot encoding, binning, polynomial features, and interaction terms.",
        "Model evaluation is critical for understanding how well a machine learning model will generalize to unseen data. Common metrics include accuracy, precision, recall, F1-score, ROC-AUC for classification, and MSE, RMSE, MAE, R-squared for regression. Cross-validation helps estimate model performance more reliably than a single train-test split.",
        "Hyperparameter tuning optimizes the configuration settings that control the learning process. Grid search exhaustively tests all parameter combinations. Random search samples parameters randomly and is often more efficient. Bayesian optimization uses probabilistic models to guide the search toward promising configurations.",
        "Ensemble methods combine multiple models to produce better predictions than any single model. Bagging (Bootstrap Aggregating) trains multiple models on random subsets of the data. Boosting sequentially trains models, with each new model focusing on the errors of the previous ones. Stacking uses a meta-learner to combine predictions from multiple base models.",
        "Transfer learning leverages knowledge gained from one task to improve performance on a related task. Pre-trained models like BERT, GPT, ResNet, and VGG serve as starting points for fine-tuning on specific downstream tasks. This approach dramatically reduces the amount of labeled data and compute resources needed.",
    ]),
    ("Cloud Architecture Design Patterns", [
        "Cloud architecture design patterns are reusable solutions to common problems in cloud computing. These patterns help architects design scalable, reliable, and cost-effective systems. Understanding these patterns is essential for building modern distributed applications.",
        "The Circuit Breaker pattern prevents an application from repeatedly trying to execute an operation that is likely to fail. When the number of failures crosses a threshold, the circuit breaker trips and all subsequent calls return an error immediately without attempting the operation. After a timeout period, the circuit breaker allows a limited number of test requests through.",
        "The CQRS (Command Query Responsibility Segregation) pattern separates read and write operations into different models. The write model handles commands that change state, while the read model handles queries. This separation allows each model to be optimized independently. Event sourcing is often used alongside CQRS to store all state changes as a sequence of events.",
        "The Saga pattern manages data consistency across microservices in distributed transaction scenarios. Instead of a single ACID transaction, a saga is a sequence of local transactions where each step publishes an event that triggers the next step. If a step fails, compensating transactions are executed to undo the preceding steps.",
        "The Strangler Fig pattern incrementally migrates a legacy system by gradually replacing specific pieces of functionality with new services. New functionality is built as separate services that coexist with the legacy system. Over time, the new services take over more functionality until the legacy system can be decommissioned.",
        "The Event Sourcing pattern stores all changes to application state as a sequence of events. Instead of storing just the current state, every state change is captured as an immutable event. The current state can be reconstructed by replaying all events. This provides a complete audit trail and enables temporal queries.",
        "The Sidecar pattern deploys components of an application into a separate process or container to provide isolation and encapsulation. The sidecar shares the same lifecycle as the parent application. Common uses include logging, monitoring, service mesh proxies, and configuration management.",
        "The Bulkhead pattern isolates elements of an application into pools so that if one fails, the others continue to function. Named after the watertight compartments in a ship's hull, this pattern prevents a failure in one part of the system from cascading to other parts. Thread pools, connection pools, and separate service instances are common implementations.",
        "The Retry pattern enables an application to handle transient failures by transparently retrying a failed operation. Transient faults include momentary loss of network connectivity, temporary unavailability of a service, or timeouts. The pattern typically uses exponential backoff with jitter to avoid thundering herd problems.",
        "The Ambassador pattern creates helper services that send network requests on behalf of a consumer service. The ambassador acts as an out-of-process proxy that handles cross-cutting concerns like retry logic, circuit breaking, routing, and monitoring. This offloads connectivity tasks from the application code.",
    ]),
    ("Database Systems and Query Optimization", [
        "Modern database systems form the backbone of virtually all software applications. From traditional relational databases to NoSQL stores, graph databases, and time-series databases, choosing the right database technology is critical for application performance and scalability.",
        "Relational databases use structured query language (SQL) and store data in tables with predefined schemas. ACID properties (Atomicity, Consistency, Isolation, Durability) ensure transaction reliability. PostgreSQL, MySQL, SQL Server, and Oracle are leading relational database management systems used in production environments worldwide.",
        "Query optimization is the process of selecting the most efficient execution plan for a SQL query. The query optimizer considers multiple factors: available indexes, table statistics, join algorithms, and data distribution. Cost-based optimizers estimate the computational cost of different execution plans and choose the least expensive one.",
        "Index design significantly impacts query performance. B-tree indexes support range queries and equality lookups efficiently. Hash indexes provide constant-time lookups for equality queries. Covering indexes include all columns referenced by a query, eliminating the need to access the base table. Composite indexes support multi-column queries but column ordering matters.",
        "NoSQL databases emerged to address limitations of relational databases in handling large-scale distributed data. Document databases like MongoDB store semi-structured data as JSON-like documents. Key-value stores like Redis offer extremely fast lookups. Column-family stores like Cassandra handle write-heavy workloads across distributed clusters. Graph databases like Neo4j efficiently traverse relationships.",
        "Database partitioning splits large tables into smaller, more manageable pieces. Horizontal partitioning (sharding) distributes rows across multiple nodes. Vertical partitioning splits a table by columns. Range partitioning assigns rows based on value ranges. Hash partitioning uses a hash function for even distribution.",
        "Replication strategies provide high availability and read scalability. Master-slave replication routes all writes to a primary node and replicates data to read replicas. Multi-master replication allows writes on any node but requires conflict resolution. Synchronous replication ensures data consistency but adds latency. Asynchronous replication offers better performance but risks data loss.",
        "Transaction isolation levels control how concurrent transactions interact. Read Uncommitted allows dirty reads. Read Committed prevents dirty reads but allows non-repeatable reads. Repeatable Read prevents non-repeatable reads but allows phantom reads. Serializable provides the highest isolation but the lowest concurrency.",
        "Write-ahead logging (WAL) ensures data integrity by writing all modifications to a log before applying them to the database pages. In case of a crash, the database can recover by replaying the log entries. This mechanism is fundamental to crash recovery in systems like PostgreSQL, SQLite, and most modern databases.",
        "Connection pooling reduces the overhead of establishing database connections. Instead of creating a new connection for each request, connections are reused from a pool. This dramatically improves throughput and reduces latency. Tools like PgBouncer, HikariCP, and connection pool libraries in various frameworks manage this efficiently.",
    ]),
    ("Cybersecurity Fundamentals and Threat Landscape", [
        "Cybersecurity encompasses the practices, technologies, and processes designed to protect networks, devices, programs, and data from attack, damage, or unauthorized access. As digital transformation accelerates, the threat landscape continues to evolve with increasingly sophisticated attacks.",
        "The MITRE ATT&CK framework is a globally accessible knowledge base of adversary tactics and techniques based on real-world observations. It covers the full attack lifecycle from initial reconnaissance through execution, persistence, privilege escalation, defense evasion, credential access, discovery, lateral movement, collection, command and control, exfiltration, and impact.",
        "Zero Trust Architecture operates on the principle of never trust, always verify. Every access request is treated as if it originates from an untrusted network, regardless of whether the request is from inside or outside the organization's perimeter. This approach requires strict identity verification, micro-segmentation, and least privilege access for every user, device, and application.",
        "Cryptography forms the mathematical foundation of cybersecurity. Symmetric encryption algorithms like AES use the same key for encryption and decryption. Asymmetric encryption like RSA uses a public-private key pair. Hash functions like SHA-256 produce fixed-length digests. Digital signatures combine hashing and asymmetric encryption for authentication and integrity.",
        "Common vulnerability types include SQL injection, cross-site scripting (XSS), cross-site request forgery (CSRF), buffer overflows, and authentication bypass. The OWASP Top 10 provides a standard awareness document for developers about the most critical web application security risks. Regular security audits and penetration testing help identify and remediate vulnerabilities.",
        "Security Information and Event Management (SIEM) platforms aggregate and correlate security data from across the organization. They collect logs from firewalls, intrusion detection systems, endpoints, servers, and applications. Advanced SIEM platforms use machine learning to detect anomalies and automate threat response through SOAR (Security Orchestration, Automation, and Response).",
        "Incident response follows a structured process: preparation, identification, containment, eradication, recovery, and lessons learned. Having a well-documented incident response plan and trained response team is critical. Tabletop exercises and simulated attacks help teams practice their response procedures before a real incident occurs.",
        "Supply chain attacks target the software development and delivery pipeline. Attackers compromise a trusted vendor, library, or build system to distribute malicious code to downstream consumers. Notable examples include the SolarWinds and Codecov attacks. Software Bill of Materials (SBOM) and code signing help mitigate these risks.",
        "Cloud security introduces unique challenges including shared responsibility models, identity federation, data sovereignty, and multi-tenancy risks. Cloud Security Posture Management (CSPM) tools continuously monitor cloud configurations for security risks. Cloud Workload Protection Platforms (CWPP) secure workloads running in cloud environments.",
        "Ransomware has become one of the most prevalent and damaging cyber threats. Modern ransomware groups use double extortion tactics, first exfiltrating sensitive data and then encrypting systems. Defense strategies include regular offline backups, network segmentation, endpoint detection and response (EDR), and employee security awareness training.",
    ]),
    ("Distributed Systems and Consensus Algorithms", [
        "Distributed systems are collections of independent computers that appear to users as a single coherent system. They provide scalability, fault tolerance, and geographic distribution. However, they introduce complexities around consistency, availability, partition tolerance, latency, and failure handling.",
        "The CAP theorem, formulated by Eric Brewer, states that a distributed system can only guarantee two of three properties simultaneously: Consistency (all nodes see the same data at the same time), Availability (every request receives a response), and Partition tolerance (the system continues to operate despite network partitions). In practice, since network partitions are unavoidable, systems must choose between consistency and availability.",
        "The Paxos algorithm, developed by Leslie Lamport, solves the consensus problem in asynchronous distributed systems. It ensures that a group of nodes can agree on a single value even if some nodes fail. Multi-Paxos extends the basic protocol to efficiently agree on a sequence of values, which is useful for implementing replicated state machines.",
        "Raft was designed as a more understandable alternative to Paxos. It decomposes consensus into three sub-problems: leader election, log replication, and safety. A Raft cluster has exactly one leader that manages log replication to follower nodes. If the leader fails, a new leader is elected through a voting mechanism. Raft is used in etcd, CockroachDB, and many other systems.",
        "Vector clocks provide a mechanism for tracking causality in distributed systems. Each process maintains a vector of logical clocks, one for each process in the system. When events are concurrent (neither happened before the other), vector clocks detect this, enabling conflict resolution strategies. They are used in systems like Amazon DynamoDB and Riak.",
        "Gossip protocols (epidemic protocols) disseminate information in distributed systems by having each node periodically exchange state with random peers. This approach is highly scalable and fault-tolerant, as information eventually reaches all nodes even with node failures. Applications include failure detection, membership management, and aggregate computation.",
        "Consistent hashing minimizes key redistribution when nodes join or leave a distributed system. Keys and nodes are mapped onto a hash ring, and each key is assigned to the nearest node clockwise on the ring. Virtual nodes improve load balancing by assigning multiple positions on the ring to each physical node.",
        "The Two-Phase Commit (2PC) protocol ensures atomic commitment across distributed nodes. In the prepare phase, the coordinator asks all participants if they can commit. In the commit phase, if all participants agreed, the coordinator instructs them to commit; otherwise, it instructs them to abort. 2PC is blocking — if the coordinator fails during the second phase, participants may be stuck waiting.",
        "CRDTs (Conflict-free Replicated Data Types) are data structures that can be replicated across multiple nodes and updated independently without coordination. All replicas are guaranteed to converge to the same state. Examples include G-Counters, PN-Counters, OR-Sets, and LWW-Registers. CRDTs enable eventual consistency without conflict resolution.",
        "Byzantine fault tolerance (BFT) addresses scenarios where nodes may behave arbitrarily, including sending incorrect or contradictory messages. The PBFT algorithm requires 3f+1 nodes to tolerate f Byzantine faults. BFT is essential for blockchain systems and any environment where nodes cannot be fully trusted.",
    ]),
    ("Natural Language Processing and Large Language Models", [
        "Natural Language Processing (NLP) is a field at the intersection of computer science, artificial intelligence, and linguistics. It focuses on the interaction between computers and human language, enabling machines to read, understand, interpret, and generate text in a way that is meaningful and useful.",
        "The transformer architecture, introduced in the landmark 2017 paper Attention Is All You Need, revolutionized NLP. Transformers use self-attention mechanisms to process all positions in a sequence simultaneously, enabling massive parallelization during training. The architecture consists of encoder and decoder stacks, each composed of multi-head attention layers and feed-forward networks.",
        "BERT (Bidirectional Encoder Representations from Transformers) introduced bidirectional pre-training by using masked language modeling and next sentence prediction objectives. BERT learns contextual representations by attending to both left and right context in all layers. It achieves state-of-the-art results on a wide range of NLP benchmarks including question answering, sentiment analysis, and named entity recognition.",
        "GPT (Generative Pre-trained Transformer) models use autoregressive language modeling, predicting the next token given all previous tokens. GPT-2 demonstrated surprising text generation capabilities. GPT-3 with 175 billion parameters showed that scaling model size leads to emergent abilities like few-shot learning. GPT-4 further improved reasoning, coding, and multimodal capabilities.",
        "Tokenization is the process of converting raw text into a sequence of tokens that the model can process. Byte Pair Encoding (BPE) iteratively merges the most frequent character pairs. WordPiece tokenization splits words into subword units. SentencePiece provides a language-independent tokenization framework. Tokenization choices affect model vocabulary size, out-of-vocabulary handling, and computation efficiency.",
        "Fine-tuning adapts a pre-trained model to a specific task or domain. Full fine-tuning updates all model parameters. Parameter-efficient methods like LoRA (Low-Rank Adaptation) and adapters freeze most parameters and only train small additional modules. Instruction tuning trains models to follow natural language instructions. RLHF (Reinforcement Learning from Human Feedback) aligns models with human preferences.",
        "Retrieval-Augmented Generation (RAG) combines information retrieval with text generation. Instead of relying solely on parametric knowledge stored in model weights, RAG retrieves relevant documents from an external knowledge base and uses them as context for generation. This approach improves factual accuracy, enables knowledge updates without retraining, and provides source attribution.",
        "Embedding models convert text into dense vector representations that capture semantic meaning. Similar texts produce similar vectors, enabling semantic search and similarity comparison. Models like text-embedding-3-small, BGE, and E5 are optimized for embedding quality. These vectors are stored in vector databases for efficient nearest-neighbor search.",
        "Prompt engineering is the practice of crafting effective prompts to elicit desired behaviors from language models. Techniques include few-shot prompting (providing examples), chain-of-thought prompting (encouraging step-by-step reasoning), and system prompts (setting the model's role and behavior). Prompt design significantly impacts model output quality and task performance.",
        "Challenges in LLM deployment include hallucination (generating plausible but incorrect information), context window limitations, inference latency and cost, data privacy concerns, and alignment with human values. Techniques like grounding, fact-checking, guardrails, and constitutional AI help address these challenges in production systems.",
    ]),
    ("Kubernetes Deep Dive and Container Orchestration", [
        "Kubernetes (K8s) is an open-source container orchestration platform originally designed by Google. It automates deployment, scaling, and management of containerized applications. The architecture consists of a control plane (API server, etcd, scheduler, controller manager) and worker nodes (kubelet, kube-proxy, container runtime).",
        "Pods are the smallest deployable units in Kubernetes. A Pod encapsulates one or more containers that share network namespace and storage volumes. Containers within a Pod communicate via localhost. Init containers run before app containers to perform setup tasks. Sidecar containers run alongside the main container to provide supporting functionality.",
        "Deployments manage ReplicaSets which in turn manage Pods. They provide declarative updates, rolling deployments, and rollback capabilities. The deployment controller continuously reconciles the desired state with the actual state. StatefulSets handle stateful applications that require stable network identities and persistent storage.",
        "Services provide stable networking for Pods. ClusterIP services are accessible only within the cluster. NodePort services expose ports on every node. LoadBalancer services provision external load balancers. Headless services (clusterIP: None) enable direct Pod-to-Pod communication, useful for StatefulSets.",
        "ConfigMaps and Secrets manage configuration data and sensitive information respectively. ConfigMaps store non-confidential key-value pairs that can be consumed as environment variables, command-line arguments, or configuration files. Secrets store sensitive data like passwords, tokens, and TLS certificates in base64-encoded form.",
        "Horizontal Pod Autoscaler (HPA) automatically scales the number of Pod replicas based on observed CPU utilization, memory usage, or custom metrics. Vertical Pod Autoscaler (VPA) adjusts resource requests and limits for containers. Cluster Autoscaler adds or removes nodes based on pending Pods and node utilization.",
        "Persistent Volumes (PV) and Persistent Volume Claims (PVC) abstract storage from Pods. Storage Classes define different tiers of storage with specific provisioners and parameters. Dynamic provisioning automatically creates PVs when PVCs are created. CSI (Container Storage Interface) drivers enable integration with various storage backends.",
        "Network Policies control Pod-to-Pod communication at the IP address or port level. They define ingress and egress rules using label selectors. Without Network Policies, all Pods in a namespace can communicate freely. Implementing Network Policies is essential for microsegmentation and defense-in-depth security strategies.",
        "Helm is the package manager for Kubernetes. Helm Charts are collections of templates that generate Kubernetes manifests. Charts support parameterization through values files, enabling environment-specific configurations. Chart dependencies allow composing complex applications from reusable components. Helm manages chart releases and supports rollback.",
        "Kubernetes operators extend the platform's capabilities by encoding operational knowledge in software. They use Custom Resource Definitions (CRDs) to define new resource types and custom controllers to implement domain-specific logic. Operators automate tasks like database provisioning, backup, scaling, and failure recovery.",
    ]),
    ("Quantum Computing and Its Applications", [
        "Quantum computing harnesses quantum mechanical phenomena — superposition, entanglement, and interference — to process information in fundamentally different ways than classical computers. While classical bits exist in states of 0 or 1, quantum bits (qubits) can exist in superpositions of both states simultaneously.",
        "Quantum gates manipulate qubits analogously to how logic gates manipulate classical bits. The Hadamard gate creates superposition states. The CNOT gate creates entanglement between qubits. The Pauli gates (X, Y, Z) perform rotations on the Bloch sphere. Universal gate sets like {H, T, CNOT} can approximate any unitary operation to arbitrary precision.",
        "Quantum entanglement is a phenomenon where qubits become correlated in ways that have no classical counterpart. Measuring one entangled qubit instantly determines the state of the other, regardless of the distance between them. Entanglement is a key resource for quantum computing, quantum cryptography, and quantum teleportation.",
        "Shor's algorithm can factor large integers exponentially faster than the best known classical algorithms. This has profound implications for RSA cryptography, which relies on the difficulty of factoring large numbers. A sufficiently powerful quantum computer running Shor's algorithm could break widely used public-key encryption schemes.",
        "Grover's algorithm provides a quadratic speedup for unstructured search problems. Instead of O(N) queries needed classically, Grover's algorithm finds a marked item in an unsorted database of N items using only O(sqrt(N)) queries. This speedup applies to any problem that can be formulated as a search problem.",
        "Quantum error correction is essential for building practical quantum computers because qubits are extremely susceptible to decoherence and noise. The surface code is the leading error correction scheme, using a 2D array of physical qubits to encode a single logical qubit. Achieving fault-tolerant quantum computing requires error rates below a certain threshold.",
        "Variational Quantum Eigensolver (VQE) and Quantum Approximate Optimization Algorithm (QAOA) are hybrid quantum-classical algorithms designed for near-term quantum devices. VQE estimates the ground state energy of molecular systems, with applications in drug discovery and materials science. QAOA addresses combinatorial optimization problems.",
        "Quantum machine learning explores the intersection of quantum computing and machine learning. Quantum kernel methods, quantum neural networks, and quantum feature maps leverage quantum properties to potentially achieve advantages in classification and pattern recognition tasks. However, proving quantum advantage for practical ML problems remains an active research area.",
        "Current quantum hardware platforms include superconducting circuits (IBM, Google), trapped ions (IonQ, Quantinuum), photonic systems (Xanadu, PsiQuantum), and neutral atoms (QuEra, Pasqal). Each platform has different trade-offs in terms of qubit quality, connectivity, gate speeds, and scalability.",
        "Quantum supremacy (or quantum advantage) refers to a quantum computer solving a problem that no classical computer can solve in a reasonable time. Google claimed supremacy in 2019 with their Sycamore processor. However, the practical utility of these demonstrations remains debated, as the problems solved have limited real-world applications.",
    ]),
    ("Biotechnology and Genetic Engineering", [
        "Biotechnology applies biological systems, living organisms, and their derivatives to develop products and technologies. Modern biotechnology encompasses genetic engineering, genomics, proteomics, bioinformatics, and synthetic biology. These fields are transforming medicine, agriculture, energy, and environmental remediation.",
        "CRISPR-Cas9 has revolutionized genetic engineering by providing a precise, efficient, and relatively inexpensive method for editing DNA. The system uses a guide RNA to direct the Cas9 nuclease to a specific genomic location, where it creates a double-strand break. The cell's repair mechanisms then introduce desired changes. Applications include gene therapy, crop improvement, and disease modeling.",
        "Gene therapy treats diseases by introducing, altering, or replacing genetic material within a patient's cells. In vivo gene therapy delivers therapeutic genes directly into the body using viral or non-viral vectors. Ex vivo gene therapy modifies cells outside the body before transplanting them back. CAR-T cell therapy, which engineers a patient's T cells to fight cancer, is a notable success story.",
        "Whole genome sequencing reads all 3.2 billion base pairs of the human genome. Next-generation sequencing (NGS) technologies have reduced the cost from billions of dollars to under a thousand dollars per genome. Long-read sequencing platforms like Oxford Nanopore and PacBio can sequence long DNA fragments, improving genome assembly and structural variant detection.",
        "Pharmacogenomics studies how genetic variation affects drug response. By analyzing a patient's genetic profile, clinicians can predict which medications will be most effective and which may cause adverse reactions. This enables personalized medicine, where treatment plans are tailored to individual genetic makeup.",
        "Synthetic biology designs and constructs new biological parts, devices, and systems. It applies engineering principles to biology, using standardized genetic parts (BioBricks) to build genetic circuits. Applications include biosensors, biofuels, pharmaceutical production, and bioremediation of environmental pollutants.",
        "mRNA technology, proven successful in COVID-19 vaccines, represents a new paradigm in therapeutics. mRNA molecules instruct cells to produce specific proteins that trigger immune responses. Beyond vaccines, mRNA therapeutics are being explored for cancer immunotherapy, rare genetic diseases, and protein replacement therapies.",
        "Epigenetics studies heritable changes in gene expression that do not involve changes to the DNA sequence. DNA methylation, histone modifications, and non-coding RNA molecules regulate gene expression. Epigenetic reprogramming is key to stem cell biology and cellular differentiation. Aberrant epigenetic patterns are associated with cancer and other diseases.",
        "Organoids are three-dimensional tissue cultures that replicate the structure and function of organs. Derived from stem cells, organoids can model brain development, intestinal diseases, and tumor biology. They serve as platforms for drug testing and personalized medicine, reducing the need for animal models.",
        "Agricultural biotechnology develops genetically modified organisms (GMOs) with improved traits such as pest resistance, drought tolerance, enhanced nutritional content, and increased yield. Golden Rice, engineered to produce beta-carotene, addresses vitamin A deficiency. Gene editing techniques like CRISPR offer more precise modifications than traditional transgenic approaches.",
    ]),
    ("Advanced Data Engineering and Pipeline Architecture", [
        "Data engineering focuses on designing, building, and maintaining the infrastructure and systems for collecting, storing, processing, and analyzing large volumes of data. Modern data engineering encompasses batch processing, stream processing, data lakes, data warehouses, and data mesh architectures.",
        "Apache Kafka is a distributed event streaming platform capable of handling trillions of events per day. Kafka's architecture consists of producers, consumers, brokers, topics, and partitions. Topics are split into partitions for parallel processing and replication for fault tolerance. Kafka Connect provides pre-built connectors for common data sources and sinks.",
        "Apache Spark is a unified analytics engine for large-scale data processing. Spark's core abstraction is the Resilient Distributed Dataset (RDD), an immutable distributed collection of objects. Spark SQL provides structured data processing. Spark Streaming handles real-time data. MLlib offers machine learning capabilities. GraphX enables graph analytics.",
        "The medallion architecture organizes data in a lakehouse into bronze (raw), silver (cleaned and conformed), and gold (business-level aggregates) layers. Each layer progressively refines data quality and structure. Bronze captures raw data with minimal transformation. Silver applies schema enforcement, deduplication, and business rules. Gold provides purpose-built datasets for analytics and reporting.",
        "Data quality encompasses accuracy, completeness, consistency, timeliness, validity, and uniqueness of data. Great Expectations and dbt tests provide automated data quality validation. Data contracts define the schema, semantics, and SLAs between data producers and consumers. Data observability tools like Monte Carlo and Bigeye detect data anomalies in production.",
        "Change Data Capture (CDC) identifies and captures changes made to a database and delivers them in real-time to downstream consumers. Debezium is a popular open-source CDC platform that reads database transaction logs. CDC enables real-time data synchronization, event-driven architectures, and incremental data processing without full table scans.",
        "Apache Airflow is a platform for programmatically authoring, scheduling, and monitoring workflows. DAGs (Directed Acyclic Graphs) define task dependencies. Operators execute specific tasks like running SQL queries, calling APIs, or triggering Spark jobs. The scheduler manages workflow execution based on defined schedules and dependencies.",
        "Data lakehouse architecture combines the best features of data lakes and data warehouses. It provides the scalability and low-cost storage of data lakes with the data management features and ACID transactions of data warehouses. Delta Lake, Apache Iceberg, and Apache Hudi are open table formats that enable lakehouse capabilities on existing data lakes.",
        "Schema evolution handles changes to data structures over time without breaking existing consumers. Forward compatibility allows new producers to send data that old consumers can read. Backward compatibility allows old producers to send data that new consumers can read. Full compatibility provides both. Apache Avro and Protocol Buffers support schema evolution natively.",
        "Data mesh is a sociotechnical approach that decentralizes data ownership to domain teams. Each domain team owns, produces, and serves their data as a product. A self-serve data infrastructure platform provides tools for domain teams to build and manage their data pipelines. Federated computational governance ensures interoperability and compliance across domains.",
    ]),
]

uploaded = 0
for i, (title, paragraphs) in enumerate(large_docs):
    doc = fitz.open()
    # Create multiple pages
    page_num = 0
    y = 80
    page = doc.new_page()
    page.insert_text((72, y), title, fontsize=18, fontname="helv")
    y = 120

    for para in paragraphs:
        # Word-wrap the paragraph
        words = para.split()
        lines = []
        line = ""
        for w in words:
            if len(line + " " + w) > 85:
                lines.append(line)
                line = w
            else:
                line = (line + " " + w).strip()
        if line:
            lines.append(line)

        for ln in lines:
            if y > 750:
                page = doc.new_page()
                y = 72
                page_num += 1
            page.insert_text((72, y), ln, fontsize=10)
            y += 14
        y += 10  # paragraph spacing

    data = doc.tobytes()
    doc.close()
    name = f"large-{i+1:03d}-{title.lower().replace(' ', '-')[:50]}.pdf"
    cc.upload_blob(name, data, overwrite=True)
    uploaded += 1
    print(f"  [{uploaded}] {name} ({page_num+1} pages, {len(data)} bytes)")

print(f"\nDone! Uploaded {uploaded} large PDFs to blobomnivectest")
